---
- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-dev-embedded"
    package_depends:
    - arduino-mk
    - avrdude
    - avrdude-doc
    - libusb-1.0-0-dev
    - libusb-1.0-doc
